# Generated by Django 4.1.2 on 2022-10-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_somemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='display',
            new_name='display_type',
        ),
    ]
